# Generated by Django 4.1.7 on 2023-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('adventure_rank', models.SmallIntegerField()),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
