# Generated by Django 4.1.7 on 2023-02-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adventure_rank',
            new_name='world_level',
        ),
    ]
